# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for tname: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Sync
      uses: joshcai/leetcode-sync@v1.4
      with:
        github-token: ${{ leetcode sync }}
        leetcode-csrf-token: ${{ secrets.LEETCODE_TOKEN }}
        leetcode-session: ${{ secrets.LEETCODE_SESSION }}
